# app/utils/strings.py
from flask import session
from app.utils.icons import display_item_name

MESSAGES = {
    'uk': {
        'nav_personal': "Особистий",
        'nav_shared': "Спільний",
        'nav_analytics': "Аналітика",
        'nav_integrations': "Інтеграції",
        'nav_theme': "Тема",
        'nav_logout': "Вийти",
        'nav_login': "Вхід",
        'nav_lang_btn': "UA",
        
        'title_personal': "Розумні Фінанси",
        'title_shared': "Спільний Бюджет",
        'total_balance': "Баланс",
        'accounts': "Рахунки",
        'goals': "Цілі",
        'transactions': "Останні транзакції",
        'add_transaction': "Додати запис",
        'type': "Тип",
        'category': "Категорія",
        'amount': "Сума",
        'description': "Опис",
        'date': "Дата",
        'save': "Зберегти",
        'delete': "Видалити",
        'edit': "Редагувати",
        'cancel': "Скасувати",
        'edit_record': "Редагувати запис",
        'edit_account': "Редагувати рахунок",
        'edit_goal': "Редагувати ціль",
        
        'income': "Дохід",
        'expense': "Витрата",
        'income_plural': "Доходи",
        'expense_plural': "Витрати",
        
        'ph_amount': "(грн)",
        'ph_desc': "(необов'язково)",
        'ph_name': "(Назва)",
        'btn_record': "Записати операцію",
        'btn_ai_auto': "Фото",
        'cat_mgmt': "Управління категоріями",
        'all_accounts': "Всі рахунки",
        'currency': "₴",
        'unit_per_day': "₴/день",
        
        'login_title': "Вхід в систему",
        'username_label': "Логін",
        'password_label': "Пароль",
        'login_btn': "Увійти",
        'no_acc_yet': "Немає аккаунту?",
        'registration_link': "Реєстрація",
        'already_have_acc': "Вже є аккаунт?",
        'register_btn': "Зареєструватися",
        'register_title': "Реєстрація",
        
        'bank_monobank': "💳 Monobank",
        'bank_privat': "ПриватБанк",
        'bank_euro': "Європейські Банки",
        'dev_status': "Розробка",
        'soon_btn': "Скоро",
        
        'filters': {
            'today': "Сьогодні",
            'month': "Цей Місяць",
            'year': "Цей Рік",
            'all': "Всі часи"
        },
        
        'filter_btn_day': "За день",
        'filter_btn_month': "За місяць",
        'filter_btn_year': "За рік",
        'filter_btn_all': "Весь час",
        
        'analytics_title': "Розумна Аналітика",
        'stats_title': "Статистика за {days} дн.",
        'chart_dist': "Розподіл витрат",
        'chart_hint': "*Наведіть на сектор, щоб побачити %",
        'top_category': "Топ категорія",
        'daily_avg': "Середня витрата",
        'budget_runway': "Запас:",
        'trends_title': "Тренди та Поради",
        'ai_analyst_title': "ШІ Фінансовий Аналітик",
        'ai_analyst_desc': "ШІ проаналізує ваші витрати та надасть персональні поради.",
        'ai_btn_eval': "Оцінка витрат",
        'ai_btn_savings': "Поради з економії",
        'ai_btn_runway': "Аналіз стійкості",
        'ai_btn_goals': "Розрахунок цілей",
        'ai_custom_query_label': "Запитати ІІ про фінанси:",
        'ai_custom_query_ph': "Наприклад: Скільки я витратив на каву минулого тижня? Або: Як мені швидше назбирати на машину?",
        'ai_btn_custom': "Запитати",
        'ai_conclusion': "Висновок ШІ:",
        'ai_analyzing': "Аналізую...",
        'ai_cooldown': "Зачекайте {remaining} сек перед наступним ШІ-аналізом (ліміт).",
        
        'total_expense_label': "Всього витрачено:",
        'no_trends_data': "Недостатньо даних для аналізу трендів.",
        'system_observations': "Що видно по даних:",
        'trend_compare_hint': "Порівняння з попереднім періодом: {days} днів",
        'no_expenses': "Немає записів для графіка",
        'no_data_comparison': "Немає даних для порівняння з попереднім періодом",
        'rec_balanced': "Ваш бюджет виглядає збалансованим. Доходи та витрати тримаються у здоровому діапазоні.",
        'rec_food_high': "Витрати на їжу перевищують 40% бюджету. Спробуйте трохи частіше готувати вдома.",
        'rec_entertainment_high': "Витрати на розваги високі (понад 20% бюджету). Перевірте, чи це нормально для вашого періоду.",
        'rec_transport_high': "Витрати на транспорт високі (понад 15% бюджету). Можливо, є простір для економії.",
        'rec_trend_warning': "Витрати суттєво зросли порівняно з попереднім періодом. Варто звернути на це увагу.",
        
        'period_label': "Період:",
        'budget_label': "Бюджет:",
        'period_7': "7 днів",
        'period_30': "30 днів",
        'period_90': "90 днів",
        'period_365': "Рік",
        'budget_personal': "Особистий",
        'budget_shared': "Спільний",
        'no_partner': "(немає партнера)",
        
        'trend_up': "Витрати зросли на {percent}% порівняно з попереднім періодом",
        'trend_down': "Витрати зменшились на {percent}% порівняно з попереднім періодом",
        'trend_stable': "Витрати стабільні порівняно з попереднім періодом",
        
        'health_title': "Фінансове Здоров'я",
        'health_note': "Оцінка враховує запас коштів, динаміку витрат, співвідношення доходів і витрат та концентрацію витрат в одній категорії.",
        'health_great': "Чудовий стан. Ви добре тримаєте баланс між доходами, витратами та запасом коштів.",
        'health_good': "Добрий результат, але є простір для покращення балансу та запасу коштів.",
        'health_bad': "Потрібно оптимізувати витрати. Перегляньте динаміку, резерв і найбільші категорії.",
        
        'chat_title': "ШІ Асистент",
        'chat_greeting': "Привіт! Я ваш ШІ-асистент. Запитайте мене про ваші фінанси, наприклад: \"Скільки я витратив на каву?\" або \"Як мені зекономити?\"",
        'chat_cleared': "Час сесії вийшов. Чат очищено. Привіт! Я ваш ШІ-асистент. Запитайте мене про ваші фінанси.",
        'chat_placeholder': "Запитати ШІ...",
        'chat_loading': "Аналізую...",
        'chat_cooldown': "Зачекайте {remaining} сек перед наступним повідомленням (ліміт).",
        'chat_error_reload': "Запит перервано через перезавантаження сторінки.",
        'chat_error_conn': "Помилка підключення до сервера ШІ.",
        
        'forecast_empty': "Баланс порожній",
        'forecast_short': "Лише на {days} дн.!",
        'forecast_normal': "На {days} дн.",
        
        'integration_title': "Банківські інтеграції",
        'mono_connected': "Підключено",
        'mono_not_connected': "Не підключено",
        'btn_sync': "Синхронізувати",
        'btn_unlink': "Відключити",
        'token_label': "Ваш Monobank Token:",
        
        'error_ai_limit': "Ваш денний ліміт ({count}/{max}) вичерпано.",
        'error_ai_quota': "Ліміт розпізнавання фото тимчасово вичерпано. Спробуйте трохи пізніше.",
        'error_ai_server': "Помилка сервера ШІ.",
        'error_no_receipt': "Будь ласка, виберіть файл чека.",
        'error_ai_fail': "Не вдалося розпізнати чек.",
        'success_ai_receipt': "Успішно додано {count} записів!",
        
        'error_invalid_login': "Неправильний логін або пароль.",
        'error_login_exists': "Користувач з таким логіном вже існує.",
        'error_username_short': "Логін занадто короткий: мінімум 3 символи.",
        'error_username_long': "Логін занадто довгий: максимум 30 символів.",
        'error_username_spaces': "Логін не має містити пробіли.",
        'error_username_chars': "Логін може містити лише літери, цифри та нижнє підкреслення.",
        'error_password_short': "Пароль занадто короткий: мінімум 6 символів.",
        'error_fix_issues': "Виправте наступні помилки:",
        'error_user_not_found': "Користувача з таким логіном не знайдено.",
        'error_already_has_partnership': "У вас вже є активний партнер.",
        'error_invite_self': "Ви не можете запросити самого себе.",
        'error_already_shared': "Цей користувач вже має партнера.",
        'error_partnership_limit': "Помилка: партнер вже має іншу активну співпрацю.",
        'error_no_name': "Введіть назву.",
        'default_account': "💵 Готівка",
        'shared_account': "💵 Спільний рахунок",
        'success_invite_sent': "Запрошення надіслано!",
        'success_shared_created': "Спільний бюджет створено!",
        'success_csv_import': "Успішно імпортовано {count} транзакцій!",
        
        'shared_invite_title': "Запрошення!",
        'shared_invite_text': "Користувач <strong>{username}</strong> пропонує вести Спільний Бюджет.",
        'shared_accept': "Прийняти",
        'shared_reject': "Відхилити",
        'shared_with': "Спільний бюджет з {username}",
        'shared_danger_zone': "Небезпечна зона",
        'shared_leave_text': "Бажаєте припинити ведення спільного бюджету? Всі дані спільного бюджету будуть незворотно втрачені. Особисті фінанси залишаться.",
        'shared_leave_btn': "Розірвати бюджет",
        'shared_leave_confirm': "Ви впевнені? Всі дані спільного бюджету будуть незворотно втрачені і це неможливо скасувати.",
        
        'history_empty': "Історія порожня",
        'history_empty_desc': "Додайте запис або фото чека!",
        'delete_all': "Видалити всі",
        'action_label': "Дія",
        'who_added': "Хто",
        'acc_label': "Рахунок",
        'acc_name_ph': "Назва",
        'acc_balance_ph': "₴",
        'btn_create': "Створити",
        'chart_distribution': "Розподіл",
        'chart_expenses': "Витрати",
        'chart_income': "Доходи",
        'calc_from_accs': "Рахувати з:",
        'all_accs_pill': "Всі рахунки",
        'receipt_ai_title': "Розпізнати по фото",
        'receipt_ai_desc': "Завантажте фото чека і ШІ створить записи.",
        'ai_comment_label': "Вказівки для ШІ:",
        'ai_comment_ph': "Наприклад: ігноруй перекази...",
        'ai_acc_label': "Рахунок:",
        'ai_btn_recognize': "Розпізнати",
        'ai_processing': "Аналізую...",
        'csv_upload_title': "Універсальний імпорт (CSV / XLSX)",
        'csv_upload_desc': "Завантажте виписку, і ШІ автоматично розпізнає транзакції.",
        'csv_file_label': "Файл виписки:",
        'csv_analyze_btn': "Аналізувати",
        'csv_processing_btn': "Обробка...",
        'csv_cancel_btn': "✕ Скасувати",
        'csv_view_btn': "Переглянути",
        'csv_preview_title': "Попередній перегляд імпорту",
        'csv_processing_title': "Обробка файлу",
        'csv_processing_desc': "Будь ласка, зачекайте. Ви можете перейти на інші сторінки, обробка триває у фоні.",
        'csv_processing_error': "Помилка обробки файлу.",
        'csv_processing_cancelled': "Обробку скасовано.",
        'csv_error_no_data': "Дані для попереднього перегляду відсутні. Завантажте файл знову.",
        'csv_status_ai_failed': "Помилка ШІ. Спробуйте пізніше.",
        'csv_status_no_tx': "У вибраному фрагменті файлу транзакцій не знайдено.",
        'csv_status_success': "Успішно оброблено {count} транзакцій",
        'csv_preview_ready': "Попередній перегляд готовий",
        'csv_found_count': "Знайдено транзакцій:",
        
        'categories': {
            'food': '🍔 Їжа',
            'transport': '🚌 Транспорт',
            'home': '🏠 Житло',
            'coffee': '☕ Кава',
            'health': '💊 Здоров\'я',
            'entertainment': '🍿 Розваги',
            'tech': '💻 Техніка',
            'clothes': '👗 Одяг',
            'utilities': '⚡ Комуналка',
            'groceries': '🛒 Продукти',
            'salary': '💰 Зарплата',
            'gift': '🎁 Подарунок',
            'investments': '📈 Інвестиції',
            'cashback': '💸 Кешбек',
            'income_shared': '💸 Спільний дохід',
            'income_transfer': '💸 Перекази',
            'supermarket': '🛒 Супермаркет',
            'restaurants': '🍔 Ресторани',
            'rent': '🏠 Оренда',
            'other': 'Інше'
        },
        
        'ai_prompts': {
            'base_receipt': "ПРОТОКОЛ: Фіскальна ідентифікація. РОЛЬ: Модуль комп'ютерного зору. МЕТОД: Few-Shot Prompting. КРОК 1: Знайди всі товари та ціни на чеку. КРОК 2: Зістав кожен товар з найближчою категорією користувача. КРОК 3: Відформатуй у суворий JSON.",
            'analytics_evaluation': "ПРОТОКОЛ: Комплексний аудит. МЕТОД: Chain-of-Thought. КРОК 1: Проаналізуй співвідношення доходу та витрат. КРОК 2: Вияви ознаки 'ментальної бухгалтерії' або ілюзії контролю в топ-категоріях. КРОК 3: Оціни ліквідність. КРОК 4: Напиши фінальний висновок з 2-3 речень.",
            'analytics_savings': "ПРОТОКОЛ: Оптимізація витрат. МЕТОД: Chain-of-Thought. КРОК 1: Визнач категорії з високою еластичністю (розваги, кава). КРОК 2: Знайди імпульсивні покупки. КРОК 3: Дай 2 конкретні поради для зменшення ірраціональних витрат без втрати якості життя.",
            'analytics_runway': "ПРОТОКОЛ: Аналіз стійкості. МЕТОД: Chain-of-Thought. КРОК 1: Оціни хаотичність щоденних витрат. КРОК 2: Спрогнозуй дату дефіциту ліквідності на основі 'Runway'. КРОК 3: Запропонуй стратегію для збільшення фінансового горизонту.",
            'analytics_goals': "ПРОТОКОЛ: Прогноз цілей. МЕТОД: Chain-of-Thought. КРОК 1: Розрахуй час досягнення цілей при поточному тренді витрат. КРОК 2: Визнач, від яких дрібних витрат можна відмовитись. КРОК 3: Напиши, наскільки це прискорить досягнення цілі."
        }
    },
    'en': {
        'nav_personal': "Personal",
        'nav_shared': "Shared",
        'nav_analytics': "Analytics",
        'nav_integrations': "Integrations",
        'nav_theme': "Theme",
        'nav_logout': "Logout",
        'nav_login': "Login",
        'nav_lang_btn': "EN",
        
        'title_personal': "Smart Finance",
        'title_shared': "Shared Budget",
        'total_balance': "Balance",
        'accounts': "Accounts",
        'goals': "Goals",
        'transactions': "Recent Transactions",
        'add_transaction': "Add Record",
        'type': "Type",
        'category': "Category",
        'amount': "Amount",
        'description': "Description",
        'date': "Date",
        'save': "Save",
        'delete': "Delete",
        'edit': "Edit",
        'cancel': "Cancel",
        'edit_record': "Edit Record",
        'edit_account': "Edit Account",
        'edit_goal': "Edit Goal",
        
        'income': "Income",
        'expense': "Expense",
        'income_plural': "Income",
        'expense_plural': "Expenses",
        
        'ph_amount': "(uah)",
        'ph_desc': "(optional)",
        'ph_name': "(Name)",
        'btn_record': "Record",
        'btn_ai_auto': "Photo",
        'cat_mgmt': "Управління категоріями",
        'all_accounts': "All Accounts",
        'currency': "UAH",
        'unit_per_day': "UAH/day",
        
        'login_title': "Login",
        'username_label': "Username",
        'password_label': "Password",
        'login_btn': "Login",
        'no_acc_yet': "No account yet?",
        'registration_link': "Register",
        'already_have_acc': "Already have an account?",
        'register_btn': "Register",
        'register_title': "Registration",
        
        'bank_monobank': "💳 Monobank",
        'bank_privat': "PrivatBank",
        'bank_euro': "European Banks",
        'dev_status': "Development",
        'soon_btn': "Soon",
        
        'filters': {
            'today': "Today",
            'month': "This Month",
            'year': "This Year",
            'all': "All Time"
        },
        
        'filter_btn_day': "Day",
        'filter_btn_month': "Month",
        'filter_btn_year': "Year",
        'filter_btn_all': "All Time",
        
        'analytics_title': "Розумна Аналітика",
        'stats_title': "Статистика за {days} дн.",
        'chart_dist': "Розподіл витрат",
        'chart_hint': "*Hover over sector to see %",
        'top_category': "Top Category",
        'daily_avg': "Daily Average",
        'budget_runway': "Runway:",
        'trends_title': "Тренди та Поради",
        'ai_analyst_title': "ШІ Фінансовий Аналітик",
        'ai_analyst_desc': "AI will analyze your spending and provide personalized tips.",
        'ai_btn_eval': "Оцінка витрат",
        'ai_btn_savings': "Поради з економії",
        'ai_btn_runway': "Аналіз стійкості",
        'ai_btn_goals': "Розрахунок цілей",
        'ai_custom_query_label': "Запитати ІІ про фінанси:",
        'ai_custom_query_ph': "Example: How much did I spend on coffee last week? Or: How can I save for a car faster?",
        'ai_btn_custom': "Запитати",
        'ai_conclusion': "AI Conclusion:",
        'ai_analyzing': "Analyzing...",
        'ai_cooldown': "Wait {remaining} sec before the next AI analysis (limit).",
        
        'total_expense_label': "Total Spent:",
        'no_trends_data': "Not enough data for trends.",
        'system_observations': "What the data shows:",
        'trend_compare_hint': "Compared with the previous period: {days} days",
        'no_expenses': "No records for the chart",
        'no_data_comparison': "No data to compare with the previous period",
        'rec_balanced': "Your budget looks balanced. Income and expenses are staying in a healthy range.",
        'rec_food_high': "Food expenses are above 40% of the budget. Cooking at home a bit more could help.",
        'rec_entertainment_high': "Entertainment spending is high (above 20% of the budget). Check whether that matches your current period.",
        'rec_transport_high': "Transport spending is high (above 15% of the budget). There may be room to save here.",
        'rec_trend_warning': "Expenses increased significantly compared with the previous period. It is worth paying attention to this.",
        
        'period_label': "Period:",
        'budget_label': "Budget:",
        'period_7': "7 days",
        'period_30': "30 days",
        'period_90': "90 days",
        'period_365': "Year",
        'budget_personal': "Personal",
        'budget_shared': "Shared",
        'no_partner': "(no partner)",
        
        'trend_up': "Expenses increased by {percent}% compared with the previous period",
        'trend_down': "Expenses decreased by {percent}% compared with the previous period",
        'trend_stable': "Expenses are stable compared with the previous period",
        
        'health_title': "Financial Health",
        'health_note': "The score considers cash buffer, spending trend, income-to-expense ratio, and how concentrated spending is in one category.",
        'health_great': "Great shape. Your income, expenses, and cash buffer are staying in a strong balance.",
        'health_good': "Good result, but there is still room to improve your balance and cash buffer.",
        'health_bad': "Spending needs optimization. Review the trend, reserve, and biggest categories.",
        
        'chat_title': "ШІ Асистент",
        'chat_greeting': "Hello! I am your AI assistant. Ask me about your finances, for example: \"How much did I spend on coffee?\" or \"How can I save?\"",
        'chat_cleared': "Session expired. Chat cleared. Hello! I am your AI assistant. Ask me about your finances.",
        'chat_placeholder': "Ask AI...",
        'chat_loading': "Analyzing...",
        'chat_cooldown': "Wait {remaining} sec before the next message (limit).",
        'chat_error_reload': "Request interrupted due to page reload.",
        'chat_error_conn': "AI server connection error.",
        
        'forecast_empty': "Balance empty",
        'forecast_short': "Only {days} days!",
        'forecast_normal': "For {days} days",
        
        'integration_title': "Банківські інтеграції",
        'mono_connected': "Connected",
        'mono_not_connected': "Не підключено",
        'btn_sync': "Sync Data",
        'btn_unlink': "Unlink",
        'token_label': "Your Monobank Token:",
        
        'error_ai_limit': "Your daily limit ({count}/{max}) reached.",
        'error_ai_quota': "Photo recognition quota is temporarily exhausted. Please try again later.",
        'error_ai_server': "Помилка сервера ШІ.",
        'error_no_receipt': "Please select a receipt.",
        'error_ai_fail': "Failed to recognize.",
        'success_ai_receipt': "Added {count} records!",
        
        'error_invalid_login': "Invalid username or password.",
        'error_login_exists': "User with this username already exists.",
        'error_username_short': "Username too short: minimum 3 characters.",
        'error_username_long': "Username too long: maximum 30 characters.",
        'error_username_spaces': "Username must not contain spaces.",
        'error_username_chars': "Username can only contain letters, digits and underscore.",
        'error_password_short': "Password too short: minimum 6 characters.",
        'error_fix_issues': "Please fix the following issues:",
        'error_user_not_found': "User with this username not found.",
        'error_already_has_partnership': "You already have an active partner.",
        'error_invite_self': "You cannot invite yourself.",
        'error_already_shared': "This user already has a partner.",
        'error_partnership_limit': "Error: partner already has another active partnership.",
        'error_no_name': "Please enter a name.",
        'default_account': "💵 Cash",
        'shared_account': "💵 Shared account",
        'success_invite_sent': "Invitation sent!",
        'success_shared_created': "Shared budget created!",
        'success_csv_import': "Successfully imported {count} transactions!",
        
        'shared_invite_title': "Запрошення!",
        'shared_invite_text': "User <strong>{username}</strong> invites you.",
        'shared_accept': "Accept",
        'shared_reject': "Reject",
        'shared_with': "Спільний бюджет з {username}",
        'shared_danger_zone': "Danger Zone",
        'shared_leave_text': "Stop sharing budget? All shared budget data will be permanently lost. Personal finances remain.",
        'shared_leave_btn': "Розірвати бюджет",
        'shared_leave_confirm': "Are you sure? All shared budget data will be permanently lost and this cannot be undone.",
        
        'history_empty': "History is empty",
        'history_empty_desc': "Add record or photo!",
        'delete_all': "Delete All",
        'action_label': "Action",
        'who_added': "Who",
        'acc_label': "Account",
        'acc_name_ph': "Name",
        'acc_balance_ph': "₴",
        'btn_create': "Create",
        'chart_distribution': "Розподіл",
        'chart_expenses': "Expenses",
        'chart_income': "Income",
        'calc_from_accs': "Calculate from:",
        'all_accs_pill': "All accounts",
        'receipt_ai_title': "Recognize from photo",
        'receipt_ai_desc': "Upload receipt and AI will create records.",
        'ai_comment_label': "AI Instructions:",
        'ai_comment_ph': "For example: ignore transfers...",
        'ai_acc_label': "Account:",
        'ai_btn_recognize': "Recognize",
        'ai_processing': "Analyzing...",
        'csv_upload_title': "Universal import (CSV / XLSX)",
        'csv_upload_desc': "Upload a statement and AI will automatically recognize transactions.",
        'csv_file_label': "Statement file:",
        'csv_analyze_btn': "Analyze",
        'csv_processing_btn': "Обробка...",
        'csv_cancel_btn': "✕ Cancel",
        'csv_view_btn': "View",
        'csv_preview_title': "Import Preview",
        'csv_processing_title': "Processing file",
        'csv_processing_desc': "Please wait. You can navigate to other pages, processing continues in background.",
        'csv_processing_error': "File processing error.",
        'csv_processing_cancelled': "Processing cancelled.",
        'csv_error_no_data': "No preview data. Please upload the file again.",
        'csv_status_ai_failed': "AI error. Please try again later.",
        'csv_status_no_tx': "No transactions found in the selected file fragment.",
        'csv_status_success': "Successfully processed {count} transactions",
        'csv_preview_ready': "Preview ready",
        'csv_found_count': "Transactions found:",

        'categories': {
            'food': '🍔 Food',
            'transport': '🚌 Transport',
            'home': '🏠 Housing',
            'coffee': '☕ Coffee',
            'health': '💊 Health',
            'entertainment': '🍿 Entertainment',
            'tech': '💻 Tech',
            'clothes': '👗 Clothes',
            'utilities': '⚡ Utilities',
            'groceries': '🛒 Groceries',
            'salary': '💰 Salary',
            'gift': '🎁 Gift',
            'investments': '📈 Investments',
            'cashback': '💸 Cashback',
            'income_shared': '💸 Shared income',
            'income_transfer': '💸 Transfers',
            'supermarket': '🛒 Supermarket',
            'restaurants': '🍔 Restaurants',
            'rent': '🏠 Rent',
            'other': 'Other'
        },
        
        'ai_prompts': {
            'base_receipt': "PROTOCOL: Fiscal Identification. ROLE: Computer Vision Module. METHOD: Few-Shot Prompting. STEP 1: Extract all items and prices. STEP 2: Map each item to the closest user category. STEP 3: Format as strict JSON.",
            'analytics_evaluation': "PROTOCOL: Comprehensive Audit. METHOD: Chain-of-Thought. STEP 1: Analyze income/expense ratio. STEP 2: Detect 'mental accounting' or control illusion in top categories. STEP 3: Assess liquidity. STEP 4: Write a final conclusion in 2-3 sentences.",
            'analytics_savings': "PROTOCOL: Spending Optimization. METHOD: Chain-of-Thought. STEP 1: Identify high-elasticity categories (entertainment, coffee). STEP 2: Find impulse purchases. STEP 3: Give 2 specific tips to reduce irrational spending.",
            'analytics_runway': "PROTOCOL: Resilience Analysis. METHOD: Chain-of-Thought. STEP 1: Evaluate daily spending volatility. STEP 2: Forecast liquidity gap date based on 'Runway'. STEP 3: Propose a strategy to extend the financial horizon.",
            'analytics_goals': "PROTOCOL: Goal Forecasting. METHOD: Chain-of-Thought. STEP 1: Calculate time to reach goals with current trend. STEP 2: Identify small expenses to cut. STEP 3: State how much faster the goal will be reached."
        }
    }
}

def get_current_lang():
    return session.get('lang', 'uk')

def get_string(key, lang=None, **kwargs):
    if lang is None:
        lang = get_current_lang()
    text = MESSAGES.get(lang, {}).get(key)
    if text is None:
        text = MESSAGES.get('uk', {}).get(key, key)
    if isinstance(text, dict): return text
    try:
        if '{count}' in text and 'count' not in kwargs: kwargs['count'] = '?'
        if '{max}' in text and 'max' not in kwargs: kwargs['max'] = '?'
        if '{days}' in text and 'days' not in kwargs: kwargs['days'] = '?'
        if '{percent}' in text and 'percent' not in kwargs: kwargs['percent'] = '?'
        return text.format(**kwargs)
    except:
        return text

def get_category(key):
    lang = get_current_lang()
    cat = MESSAGES.get(lang, {}).get('categories', {}).get(key)
    if cat is None:
        cat = MESSAGES.get('uk', {}).get('categories', {}).get(key, key)
    return cat

def translate_name(name):
    if not name: return name
    name = display_item_name(name)
    lang = get_current_lang()
    
    cat_mapping = {
        'їжа': 'food', 'food': 'food',
        'транспорт': 'transport', 'transport': 'transport',
        'житло': 'home', 'housing': 'home',
        'кава': 'coffee', 'coffee': 'coffee',
        'здоров\'я': 'health', 'health': 'health',
        'розваги': 'entertainment', 'entertainment': 'entertainment',
        'техніка': 'tech', 'tech': 'tech',
        'одяг': 'clothes', 'clothes': 'clothes',
        'комуналка': 'utilities', 'utilities': 'utilities',
        'продукти': 'groceries', 'groceries': 'groceries',
        'зарплата': 'salary', 'salary': 'salary',
        'подарунок': 'gift', 'gift': 'gift',
        'інвестиції': 'investments', 'инвестиции': 'investments', 'investments': 'investments',
        'кешбек': 'cashback', 'cashback': 'cashback',
        'income_shared': 'income_shared', 'shared income': 'income_shared',
        'income_transfer': 'income_transfer', 'перекази': 'income_transfer',
        'переказ': 'income_transfer', 'transfer': 'income_transfer',
        'супермаркет': 'supermarket', 'supermarket': 'supermarket',
        'ресторани': 'restaurants', 'restaurants': 'restaurants',
        'оренда': 'rent', 'rent': 'rent',
        'інше': 'other', 'other': 'other'
    }
    
    name_lower = name.lower()
    for kw, key in cat_mapping.items():
        if kw in name_lower:
            return get_category(key)
            
    if "всі рахунки" in name_lower or "all accounts" in name_lower:
        return get_string('all_accs_pill')
        
    return name
